<?php

/**
 * Business rules for the users table.
 * Columns missing in MySQL are ignored; new columns can be sent in the body
 * if they exist in the table (unless excluded).
 */
return [
    'table' => 'users',

    // Must exist in the DB and have a value after registration
    'required_columns' => [
        'uuid',
        'first_name',
        'email',
        'password',
        'role',
        'status',
        'created_at',
        'updated_at',
    ],

    // Not sent by the client; generated by the server
    'server_generated' => [
        'uuid',
        'created_at',
        'updated_at',
    ],

    // Used when the column exists and the client does not send a value
    'defaults' => [
        'role' => 'user',
        'status' => 'active',
    ],

    // Never return in JSON responses
    'hidden_columns' => [
        'password',
        'token',
    ],

    // Reject from request body (security); password is validated and hashed separately
    'blocked_input' => [
        'id',
        'created_at',
        'updated_at',
        'email_verified_at',
        'last_login_at',
        'last_login_ip',
        'token',
        'token_expires_at',
        'deleted_at',
    ],

    'validation_rules' => [
        'first_name' => ['type' => 'string', 'min_length' => 2],
        'email' => ['type' => 'email'],
        'password' => ['type' => 'password'],
    ],
];
